### PR TITLE
Add ipyvolume for 3D scatter using Web GL

### PR DESCRIPTION
**Pull request by Kcedrone**
https://github.com/maartenbreddels/ipyvolume

### CODE REVIEW

**Comment by Kcedrone** [comment]
@forrestp Is this the correct procedure to ask for dependencies?

**Comment by forrestp** [comment]
@Kcedrone yep, also just add me as a reviewer for the PR so it gets added to my PR queue for a faster response. 

Unfortunately we don't have an automated way of deploying these changes yet - we'll work on improving this moving forward but in the meantime I'll manually deploy as soon as I see your requests. This involves killing/restarting your private jupyter container, so I'll try to do it in the evenings to minimize impact.

**Review by forrestp — APPROVED** [review]

**Comment by Kcedrone** [comment]
@forrestp There are some additional instructions for making it active. Do I
need to do those manually from a terminal, or is there a way to script them
to occur on initialization of the jupyter server?

**Comment by forrestp** [comment]
@Kcedrone I added these commands in #4 and just deployed it, seems to be working.

A couple thoughts on process:
* I just gave you write access on this repo and turned on branch protection for the 'master' branch, so moving forward you can submit PR's via a branch on the same repo rather than forking (should be easier).
* When additional commands are required, we need to add them to the Dockerfile- feel free to try this yourself (see #4 as an example), or at least mention in the PR that you need help adding them so I know to make the change
* For tricky things with plugins and custom graphing utilities etc., it would be great if you could include a demo notebook or link to code I can run to test that the change works. In this case, I used this example: https://ipyvolume.readthedocs.io/en/latest/#built-on-ipywidgets

**Pull request merged**
